% ChanWoo

% Plot Changes of Cable
% Function
% stringLengthHistoryVert(A,B,C)
% A: Connection number
% B: Cable Number
% C: Time Frame


figure(10)
suptitle('Changes in Length of Cables in Connection 1-2')
subplot(4,2,1)
plot(squeeze(stringLengthHistoryVert(1,1,:)))
title('Vertical Cable 1')
subplot(4,2,2)
plot(squeeze(stringLengthHistoryVert(1,2,:)))
title('Vertical Cable 2')
subplot(4,2,3)
plot(squeeze(stringLengthHistoryVert(1,3,:)))
title('Vertical Cable 3')
subplot(4,2,4)
plot(squeeze(stringLengthHistoryVert(1,4,:)))
title('Vertical Cable 4')
subplot(4,2,5)
plot(squeeze(stringLengthHistorySadd(1,1,:)))
title('Saddle Cable 1')
subplot(4,2,6)
plot(squeeze(stringLengthHistorySadd(1,2,:)))
title('Saddle Cable 2')
subplot(4,2,7)
plot(squeeze(stringLengthHistorySadd(1,3,:)))
title('Saddle Cable 3')
subplot(4,2,8)
plot(squeeze(stringLengthHistorySadd(1,4,:)))
title('Saddle Cable 4')

figure(11)
suptitle('Changes in Length of Cables in Connection 2-3')
subplot(4,2,1)
plot(squeeze(stringLengthHistoryVert(2,1,:)))
title('Vertical Cable 1')
subplot(4,2,2)
plot(squeeze(stringLengthHistoryVert(2,2,:)))
title('Vertical Cable 2')
subplot(4,2,3)
plot(squeeze(stringLengthHistoryVert(2,3,:)))
title('Vertical Cable 3')
subplot(4,2,4)
plot(squeeze(stringLengthHistoryVert(2,4,:)))
title('Vertical Cable 4')
subplot(4,2,5)
plot(squeeze(stringLengthHistorySadd(2,1,:)))
title('Saddle Cable 1')
subplot(4,2,6)
plot(squeeze(stringLengthHistorySadd(2,2,:)))
title('Saddle Cable 2')
subplot(4,2,7)
plot(squeeze(stringLengthHistorySadd(2,3,:)))
title('Saddle Cable 3')
subplot(4,2,8)
plot(squeeze(stringLengthHistorySadd(2,4,:)))
title('Saddle Cable 4')

figure(12)
suptitle('Changes in Length of Cables in Connection 3-4')
subplot(4,2,1)
plot(squeeze(stringLengthHistoryVert(3,1,:)))
title('Vertical Cable 1')
subplot(4,2,2)
plot(squeeze(stringLengthHistoryVert(3,2,:)))
title('Vertical Cable 2')
subplot(4,2,3)
plot(squeeze(stringLengthHistoryVert(3,3,:)))
title('Vertical Cable 3')
subplot(4,2,4)
plot(squeeze(stringLengthHistoryVert(3,4,:)))
title('Vertical Cable 4')
subplot(4,2,5)
plot(squeeze(stringLengthHistorySadd(3,1,:)))
title('Saddle Cable 1')
subplot(4,2,6)
plot(squeeze(stringLengthHistorySadd(3,2,:)))
title('Saddle Cable 2')
subplot(4,2,7)
plot(squeeze(stringLengthHistorySadd(3,3,:)))
title('Saddle Cable 3')
subplot(4,2,8)
plot(squeeze(stringLengthHistorySadd(3,4,:)))
title('Saddle Cable 4')

figure(13)
suptitle('Changes in Length of Cables in Connection 4-5')
subplot(4,2,1)
plot(squeeze(stringLengthHistoryVert(4,1,:)))
title('Vertical Cable 1')
subplot(4,2,2)
plot(squeeze(stringLengthHistoryVert(4,2,:)))
title('Vertical Cable 2')
subplot(4,2,3)
plot(squeeze(stringLengthHistoryVert(4,3,:)))
title('Vertical Cable 3')
subplot(4,2,4)
plot(squeeze(stringLengthHistoryVert(4,4,:)))
title('Vertical Cable 4')
subplot(4,2,5)
plot(squeeze(stringLengthHistorySadd(4,1,:)))
title('Saddle Cable 1')
subplot(4,2,6)
plot(squeeze(stringLengthHistorySadd(4,2,:)))
title('Saddle Cable 2')
subplot(4,2,7)
plot(squeeze(stringLengthHistorySadd(4,3,:)))
title('Saddle Cable 3')
subplot(4,2,8)
plot(squeeze(stringLengthHistorySadd(4,4,:)))
title('Saddle Cable 4')