syms x y z T G P
assume(x,'real');
assume(y,'real');
assume(z,'real');
assume(T,'real');
assume(G,'real');
assume(P,'real');
ct  = cos(T);
st  = sin(T);
Rxx =[1  0   0 0; ...
    0 ct -st 0; ...
    0 st  ct 0; ...
    0  0   0 1];
ct  = cos(G);
st  = sin(G);
Ryy = [ct 0 st 0; ...
    0 1  0 0; ...
    -st 0 ct 0; ...
    0 0  0 1];
ct  = cos(P);
st  = sin(P);
Rzz = [ct -st 0 0; ...
    st  ct 0 0; ...
    0   0 1 0; ...
    0   0 0 1];

Rtt = [1 0 0 x; ...
    0 1 0 y; ...
    0 0 1 z; ...
    0 0 0 1];
RR1 = simplify(Rtt*Rzz*Ryy*Rxx,100);
matlabFunction(RR1,'file','getHG_Tform','Vars',[x; y; z; T; G; P]);



