% @Author ChanWoo Yang
% UC Berkeley
% BEST Lab
% Dynamic Tensegrity Robotics Lab
% Intelligent Robotics Group, NASA Ames Research Center
% Created 4/03/2015
% Modified 4/12/2015
% Contact ChanWoo at: chanwoo.yang@berkeley.edu
% Tensegrity Spine Dynamics: Stellated Tetrahedron Segment
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [ F ] = appliedForce( l,h,F1,F2,F3,F4,F5,theta,phi,psi )
%INPUT:
% l = R*sind(alpha/2);
% h = R*cosd(alpha/2);
% F1,F2,F3,F4,F5 = Force at each node
% x,y,z,theta,phi,psi = 6 states of a segment
%OUTPUT:
% F = Force vector; 
%     Summation of forces acting on each node respect to each state

F = zeros(6,1);
drdx = [1 0 0]';
drdy = [0 1 0]';
drdz = [0 0 1]';
dr1dtheta = [0 0 0]';
dr2dtheta = [0,... 
            cosd(theta)*(-h*cosd(phi)+l*cosd(psi)*sind(phi))-l*sind(psi)*sind(theta),...
            -l*cosd(theta)*sind(psi)+(h*cosd(phi)-l*cosd(psi)*sind(phi))*sind(theta)]';
dr3dtheta = [0,...
            -cosd(theta)*(h*cosd(phi)+l*cosd(psi)*sind(phi))+l*sind(psi)*sind(theta),...
            l*cosd(theta)*sind(psi)+(h*cosd(phi)+l*cosd(psi)*sind(phi))*sind(theta)]';
dr4dtheta = [0,...
            cosd(theta)*(h*cosd(phi)+l*sind(phi)*sind(psi))+l*cosd(psi)*sind(theta),...
            l*cosd(psi)*cosd(theta)-(h*cosd(phi)+l*sind(phi)*sind(psi))*sind(theta)]';
dr5dtheta = [0,...
            h*cosd(phi)*cosd(theta)-l*(cosd(theta)*sind(phi)*sind(psi)+cosd(psi)*sind(theta)),...
            -l*cosd(psi)*cosd(theta)+(-h*cosd(phi)+l*sind(phi)*sind(psi))*sind(theta)]';
dr1dphi = [0 0 0]';
dr2dphi = [-h*cosd(phi)+l*cosd(psi)*sind(phi),...
          (l*cosd(phi)*cosd(psi)+h*sind(phi))*sind(theta),...
          (l*cosd(phi)*cosd(psi)+h*sind(phi))*cosd(theta)]';
dr3dphi = [-h*cosd(phi)-l*cosd(psi)*sind(phi),...
           -(l*cosd(phi)*cosd(psi)-h*sind(phi))*sind(theta),...
           -(l*cosd(phi)*cosd(psi)-h*sind(phi))*cosd(theta)]';
dr4dphi = [h*cosd(phi)+l*sind(phi)*sind(psi),...
          (-h*sind(phi)+l*cosd(phi)*sind(psi))*sind(theta),...
          (-h*sind(phi)+l*cosd(phi)*sind(psi))*cosd(theta)]';
dr5dphi = [h*cosd(phi)-l*sind(phi)*sind(psi),...
          (-h*sind(phi)-l*cosd(phi)*sind(psi))*sind(theta),...
          (-h*sind(phi)-l*cosd(phi)*sind(psi))*cosd(theta)]';
dr1dpsi = [0 0 0]';
dr2dpsi = [l*cosd(phi)*sind(psi),...
           l*(cosd(psi)*cosd(theta)-sind(phi)*sind(psi)*sind(theta)),...
           -l*(cosd(theta)*sind(phi)*sind(psi)+cosd(psi)*sind(theta))]';
dr3dpsi = [-l*cosd(phi)*sind(psi),...
           -l*cosd(psi)*cosd(theta)+l*sind(phi)*sind(psi)*sind(theta),...
           l*(cosd(theta)*sind(phi)*sind(psi)+cosd(psi)*sind(theta))]';
dr4dpsi = [-l*cosd(phi)*cosd(psi),...
            l*(cosd(theta)*sind(psi)+cosd(psi)*sind(phi)*sind(theta)),...
            l*(cosd(psi)*cosd(theta)*sind(phi)-sind(psi)*sind(theta))]';
dr5dpsi = [l*cosd(phi)*cosd(psi),...
          -l*(cosd(theta)*sind(psi)+cosd(psi)*sind(phi)*sind(theta)),...
          -l*cosd(psi)*cosd(theta)*sind(phi)+l*sind(psi)*sind(theta)]';

F(1) = (F1+F2+F3+F4+F5)*drdx;
F(2) = (F1+F2+F3+F4+F5)*drdy;
F(3) = (F1+F2+F3+F4+F5)*drdz;
F(4) = F1*dr1dtheta + F2*dr2dtheta + F3*dr3dtheta + F4*dr4dtheta + F5*dr5dtheta;
F(5) = F1*dr1dphi + F2*dr2dphi + F3*dr3dphi + F4*dr4dphi + F5*dr5dphi;
F(6) = F1*dr1dpsi + F2*dr2dpsi + F3*dr3dpsi + F4*dr4dpsi + F5*dr5dpsi;

end

