function lengths = two_d_spine_lengths(x2,z2,T2)
%TWO_D_SPINE_LENGTHS
%    LENGTHS = TWO_D_SPINE_LENGTHS(X2,Z2,T2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Nov-2016 16:36:16

t5 = sqrt(3.0);
t6 = t5.*(3.0./4.0e1);
t14 = pi.*(1.0./6.0);
t15 = T2+t14;
t16 = cos(t15);
t17 = t16.*(3.0./2.0e1);
t2 = abs(t6-t17+x2);
t4 = pi.*(1.0./3.0);
t10 = T2-t4;
t11 = cos(t10);
t12 = t11.*(3.0./2.0e1);
t3 = abs(-t12+z2+3.0./4.0e1);
t8 = T2+t4;
t22 = sin(t8);
t23 = t22.*(3.0./2.0e1);
t7 = abs(-t6+t23+x2);
t19 = cos(t8);
t20 = t19.*(3.0./2.0e1);
t9 = abs(-t20+z2+3.0./4.0e1);
t13 = abs(t12-z2+3.0./4.0e1);
t18 = abs(-t17+x2);
t21 = abs(t20-z2+3.0./4.0e1);
t24 = abs(t23+x2);
lengths = reshape([0.0,0.0,0.0,0.0,sqrt(t2.^2+t3.^2),sqrt(t7.^2+t9.^2),sqrt(t13.^2+t18.^2),sqrt(t21.^2+t24.^2)],[4,2]);
