function dlengths_dt_sub = two_d_spine_dlengths_dt(in1)
%TWO_D_SPINE_DLENGTHS_DT
%    DLENGTHS_DT_SUB = TWO_D_SPINE_DLENGTHS_DT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Jun-2018 18:25:11

xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
xi4 = in1(4,:);
xi5 = in1(5,:);
xi6 = in1(6,:);
t3 = sqrt(2.0);
t4 = pi.*(1.0./4.0);
t5 = t4+xi3;
t10 = cos(t5);
t11 = t3.*t10.*1.3e1;
t13 = xi1.*1.0e2;
t2 = -t11+t13+1.3e1;
t9 = xi2.*1.0e2;
t14 = sin(t5);
t15 = t3.*t14.*1.3e1;
t6 = t9-t15+1.3e1;
t7 = cos(xi3);
t8 = sin(xi3);
t12 = t9-t11+1.3e1;
t16 = t13+t15-1.3e1;
t17 = xi4.*1.3e3;
t18 = xi5.*1.3e3;
t19 = xi1.*xi4.*1.0e4;
t20 = xi2.*xi5.*1.0e4;
t21 = t8.*xi4.*1.3e3;
t22 = t8.*xi6.*3.38e2;
t23 = t7.*xi1.*xi6.*1.3e3;
t24 = t8.*xi1.*xi6.*1.3e3;
t25 = t8.*xi2.*xi6.*1.3e3;
t26 = t11-t13;
t27 = -t9+t15+1.3e1;
t28 = -t9+t11+1.3e1;
t29 = t13+t15;
dlengths_dt_sub = [1.0./sqrt(t2.^2+t6.^2).*(t17+t18+t19+t20+t21+t22+t23+t24+t25-t7.*xi4.*1.3e3-t7.*xi5.*1.3e3-t8.*xi5.*1.3e3-t7.*xi2.*xi6.*1.3e3).*(1.0./1.0e2);1.0./sqrt(t12.^2+t16.^2).*(-t17+t18+t19+t20+t21+t22+t23-t24+t25+t7.*xi4.*1.3e3-t7.*xi5.*1.3e3+t8.*xi5.*1.3e3+t7.*xi2.*xi6.*1.3e3).*(1.0./1.0e2);1.0./sqrt(t26.^2+t27.^2).*(t18-t19-t20+t3.*t10.*xi4.*1.3e3-t3.*t10.*xi6.*1.69e2+t3.*t14.*xi5.*1.3e3+t3.*t10.*xi2.*xi6.*1.3e3-t3.*t14.*xi1.*xi6.*1.3e3).*(-1.0./1.0e2);1.0./sqrt(t28.^2+t29.^2).*(-t18+t19+t20-t3.*t10.*xi5.*1.3e3+t3.*t14.*xi4.*1.3e3-t3.*t14.*xi6.*1.69e2+t3.*t10.*xi1.*xi6.*1.3e3+t3.*t14.*xi2.*xi6.*1.3e3).*(1.0./1.0e2)];
