function lengths = two_d_spine_lengths(in1)
%TWO_D_SPINE_LENGTHS
%    LENGTHS = TWO_D_SPINE_LENGTHS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Jun-2018 18:25:10

xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
t3 = sqrt(2.0);
t4 = pi.*(1.0./4.0);
t5 = t4+xi3;
t8 = cos(t5);
t9 = t3.*t8.*1.3e1;
t11 = xi1.*1.0e2;
t2 = -t9+t11+1.3e1;
t7 = xi2.*1.0e2;
t12 = sin(t5);
t13 = t3.*t12.*1.3e1;
t6 = t7-t13+1.3e1;
t10 = t7-t9+1.3e1;
t14 = t11+t13-1.3e1;
t15 = t9-t11;
t16 = -t7+t13+1.3e1;
t17 = -t7+t9+1.3e1;
t18 = t11+t13;
lengths = [sqrt(t2.^2+t6.^2).*(1.0./1.0e2);sqrt(t10.^2+t14.^2).*(1.0./1.0e2);sqrt(t15.^2+t16.^2).*(1.0./1.0e2);sqrt(t17.^2+t18.^2).*(1.0./1.0e2)];
