function tensions_sub = two_d_spine_tensions(in1,in2)
%TWO_D_SPINE_TENSIONS
%    TENSIONS_SUB = TWO_D_SPINE_TENSIONS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    05-Jun-2018 18:25:11

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
xi4 = in1(4,:);
xi5 = in1(5,:);
xi6 = in1(6,:);
t3 = sqrt(2.0);
t4 = pi.*(1.0./4.0);
t5 = t4+xi3;
t7 = xi1.*1.0e2;
t8 = cos(t5);
t9 = t3.*t8.*1.3e1;
t2 = t7-t9+1.3e1;
t11 = xi2.*1.0e2;
t12 = sin(t5);
t13 = t3.*t12.*1.3e1;
t6 = t11-t13+1.3e1;
t10 = t2.^2;
t14 = t6.^2;
t15 = t10+t14;
t16 = cos(xi3);
t17 = sin(xi3);
t18 = -t9+t11+1.3e1;
t19 = t7+t13-1.3e1;
t20 = t18.^2;
t21 = t19.^2;
t22 = t20+t21;
t23 = xi4.*1.3e3;
t24 = xi5.*1.3e3;
t25 = xi1.*xi4.*1.0e4;
t26 = xi2.*xi5.*1.0e4;
t27 = t17.*xi4.*1.3e3;
t28 = t17.*xi6.*3.38e2;
t29 = t16.*xi1.*xi6.*1.3e3;
t30 = t17.*xi1.*xi6.*1.3e3;
t31 = t17.*xi2.*xi6.*1.3e3;
t32 = t7-t9;
t33 = -t11+t13+1.3e1;
t34 = t32.^2;
t35 = t33.^2;
t36 = t34+t35;
t37 = t9-t11+1.3e1;
t38 = t7+t13;
t39 = t37.^2;
t40 = t38.^2;
t41 = t39+t40;
tensions_sub = [u1.*-2.0e3+1.0./sqrt(t15).*(t23+t24+t25+t26+t27+t28+t29+t30+t31-t16.*xi4.*1.3e3-t16.*xi5.*1.3e3-t17.*xi5.*1.3e3-t16.*xi2.*xi6.*1.3e3).*(1.0./2.0)+sqrt(t15).*2.0e1;u2.*-2.0e3+1.0./sqrt(t22).*(-t23+t24+t25+t26+t27+t28+t29-t30+t31+t16.*xi4.*1.3e3-t16.*xi5.*1.3e3+t17.*xi5.*1.3e3+t16.*xi2.*xi6.*1.3e3).*(1.0./2.0)+sqrt(t22).*2.0e1;u3.*-2.0e3-1.0./sqrt(t36).*(t24-t25-t26+t3.*t8.*xi4.*1.3e3-t3.*t8.*xi6.*1.69e2+t3.*t12.*xi5.*1.3e3+t3.*t8.*xi2.*xi6.*1.3e3-t3.*t12.*xi1.*xi6.*1.3e3).*(1.0./2.0)+sqrt(t36).*2.0e1;u4.*-2.0e3+sqrt(t41).*2.0e1+1.0./sqrt(t41).*(-t24+t25+t26-t3.*t8.*xi5.*1.3e3+t3.*t12.*xi4.*1.3e3-t3.*t12.*xi6.*1.69e2+t3.*t8.*xi1.*xi6.*1.3e3+t3.*t12.*xi2.*xi6.*1.3e3).*(1.0./2.0)];
